
#################### 不同环境配置切换 #####################
#active配置dev就是使用application-dev.yml文件
spring:
  application:
    name: comic-manager
  profiles:
    active: dev

#################### mybatis配置 #############################
mybatis:
  type-aliases-package: com.comic.miyuki.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

#################### 自定义配置 #############################
constant:
  name: system

name: 超级管理员